{% set name = "pyeee" %}
{% set version = "4.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4371c215d48f8af39edc259d0e4ae33d13990532caf12ee8c59a82a5b0271f7d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=42
    - setuptools_scm >=3.5
  run:
    - python >=3.8
    - numpy
    - scipy
    - schwimmbad !=0.4.0
    - pyjams

test:
  imports:
    - pyeee
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mcuntz/pyeee
  summary: "Parameter screening using Efficient/Sequential Elementary Effects, an extension of Morris' method by Cuntz, Mai et al. (Water Res Research, 2015)"
  dev_url: https://github.com/mcuntz/pyeee
  license: MIT
  license_file: LICENSE
  description: |
    pyeee is a Python library for performing parameter screening of
    computational models. It uses Efficient or Sequential Elementary
    Effects, an extension of Morris' method of Elementary Effects,
    published by Cuntz M, Mai J et al. (2015) Computationally
    inexpensive identification of noninformative model parameters by
    sequential screening, Water Resources Research 51, 6417-6441, doi:
    10.1002/2015WR016907. pyeee can be used with Python functions as
    well as external executables using libraries such as
    partialwrap. Function evaluations can be distributed with Python's
    multiprocessing or via the Message Passing Interface (MPI).
  doc_url: https://mcuntz.github.io/pyeee/

extra:
  recipe-maintainers:
    - mcuntz
